### ISSUE TITLE
ONNX model analyzer error: the provided PTX was compiled with an unsupported toolchain

### ISSUE THREAD

**Issue by Deseram** [triton-inference-server/model_analyzer#182] opened 2021-07-16 08:52 UTC
Error log

```
2021-07-16 08:44:13.777 WARNING[entrypoint.py:232] Overriding the output model repo path "/tmp/model_output_repo/model_output"...
2021-07-16 08:44:13.779 INFO[entrypoint.py:112] Starting a Triton Server using docker...
2021-07-16 08:44:14.888 INFO[analyzer_state_manager.py:119] No checkpoint file found, starting a fresh run.
2021-07-16 08:44:14.888 INFO[analyzer.py:80] Profiling server only metrics...
2021-07-16 08:46:18.958 INFO[gpu_monitor.py:73] Using GPU(s) with UUID(s) = { GPU-f6e2ae57-5841-b13b-c882-04fd5172d292 } for profiling.
2021-07-16 08:46:19.980 INFO[server_docker.py:128] Stopping triton server.
2021-07-16 08:46:20.614 INFO[run_search.py:292] Instance count set to 1, and dynamic batching is disabled.
2021-07-16 08:46:24.71 INFO[client.py:83] Model dpr_i0 load failed: [StatusCode.INVALID_ARGUMENT] load failed for model 'dpr_i0': version 1: Internal: onnx runtime error 1: /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:121 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:115 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 222: the provided PTX was compiled with an unsupported toolchain. ; GPU=0 ; hostname=8c086208d7cc ; expr=cudaDeviceSynchronize();

;

2021-07-16 08:46:24.71 INFO[server_docker.py:128] Stopping triton server.
2021-07-16 08:46:30.301 INFO[client.py:83] Model dpr_i0 load failed: [StatusCode.INVALID_ARGUMENT] load failed for model 'dpr_i0': version 1: Internal: onnx runtime error 1: /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:121 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:115 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 222: the provided PTX was compiled with an unsupported toolchain. ; GPU=0 ; hostname=6defe604979f ; expr=cudaDeviceSynchronize();

;

2021-07-16 08:46:30.301 INFO[server_docker.py:128] Stopping triton server.
^C2021-07-16 08:46:33.211 INFO[analyzer_state_manager.py:161] Received SIGINT 1/3. Will attempt to exit after current measurement.
^C^C2021-07-16 08:46:34.156 INFO[analyzer_state_manager.py:161] Received SIGINT 2/3. Will attempt to exit after current measurement.
2021-07-16 08:46:34.156 INFO[client.py:83] Model dpr_i0 load failed: [StatusCode.INVALID_ARGUMENT] load failed for model 'dpr_i0': version 1: Internal: onnx runtime error 1: /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:121 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:115 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 222: the provided PTX was compiled with an unsupported toolchain. ; GPU=0 ; hostname=7c238636601e ; expr=cudaDeviceSynchronize();

;

2021-07-16 08:46:34.157 INFO[server_docker.py:128] Stopping triton server.
2021-07-16 08:46:34.804 INFO[analyzer_state_manager.py:145] Saved checkpoint to ./checkpoints/0.ckpt.
2021-07-16 08:46:34.804 INFO[analyzer.py:117] Finished profiling. Obtained measurements for models: [].
2021-07-16 08:46:34.804 INFO[server_docker.py:128] Stopping triton server.
```

model analyzer command
`model-analyzer profile --config /config.yaml`

model analyzer config
```
model_repository: /triton_models
batch_sizes: [1,2,4,8,16,32,64,128,256,512,1024]
concurrency:
    start: 1
    stop: 10
    step: 2
profile_models:
    - dpr
override_output_model_repository: true
triton_launch_mode: docker
gpus: all
client_protocol: grpc
triton_grpc_endpoint: localhost:8001
output_model_repository_path: /tmp/model_output_repo/model_output
triton_docker_image: nvcr.io/nvidia/tritonserver:21.06.1-py3
triton_server_flags:
        strict_model_config: False
        log_verbose: True
```

model-analyzer docker run command
```
docker run -it --rm --gpus 0 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/model_output_repo:/tmp/model_output_repo -v /home/ubuntu/ml-stew/serving_benchmarker/model-analyzer.yaml:/config.yaml -v /home/ubuntu/ml-stew/serving_benchmarker/triton_models:/triton_models --net host nvcr.io/nvidia/tritonserver:21.06-py3-sdk
```

model-analyzer build command
```
docker pull nvcr.io/nvidia/tritonserver:21.06-py3-sdk
```

Model repo
```
triton_models
├── dpr
│   ├── 1
│   │   └── model.onnx
│   └── config.pbtxt
├── dpr-1
│   ├── 1
│   │   └── model.onnx
│   └── config.pbtxt
└── dpr.dvc
```

Model was converted from pytorch to onnx, conversion code

```
torch.onnx.export(
    context_encoder,
    sample_data.data,
    "context_encoder.onnx",
    export_params=True,
    opset_version=11,
    do_constant_folding=True,
    input_names=["input_ids","token_type_ids","attention_mask"],
    output_names=["output"],
    dynamic_axes={
        "input_ids": {0: "batch_size", 1: "sequence_length"},
        "token_type_ids": {0: "batch_size", 1: "sequence_length"},
        "attention_mask": {0: "batch_size", 1: "sequence_length"},
        "output": {0: "batch_size"},
    },
)
```

Running the triton inference server works fine on gpu, but the model analyzer fails and I've tried everything I could. Really appreciate if I can get some help here

**Comment by Tabrizian** [comment] 2021-07-19 14:38
@Deseram I think the issue is with the CUDA driver. What is the version of the CUDA and CUDA driver that you are using? What is the version of the Model Analyzer and Triton Server that is able to successfully load the model?

**Comment by Deseram** [comment] 2021-07-19 15:04
I'm running the containerised version, therefore CUDA is installed in the container.

I suspected it was a version of the serving container I was using hence I used the same version I used for initial testing, which is `nvcr.io/nvidia/tritonserver:21.06.1-py3`. 

For the Model Analyzer, I tried both `nvcr.io/nvidia/tritonserver:21.06.1-py3-skd` and `nvcr.io/nvidia/tritonserver:21.06-py3-skd` and I'm still getting the same error

**Comment by Deseram** [comment] 2021-07-19 15:05
CUDA version on the machine
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   51C    P0    70W /  70W |  12106MiB / 15109MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     23509      C   tritonserver                    12103MiB |
+-----------------------------------------------------------------------------+
```

**Comment by Tabrizian** [comment] 2021-07-19 15:14
It looks like your CUDA version is not up to date. For 21.06 the CUDA 11.3 is expected. https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

**Comment by Deseram** [comment] 2021-07-19 15:21
But how come the inference server works in the same machine. As you can see in the above image I'm already running the tritonserver there? and this is the version I mentioned earlier. Is it the SKD container that has issues with the CUDA version?

**Comment by Tabrizian** [comment] 2021-07-19 15:33
Are you running the exact same version of the inference server? MA uses 21.06 version of inference server. You can change it to use the 21.06.1 inference server using the [triton_docker_image](https://github.com/triton-inference-server/model_analyzer/blob/568897b9ad9c4e5da24a45a17b400fb604b49981/docs/config.md#cli-and-yaml-config-options) config option.

**Comment by Deseram** [comment] 2021-07-19 15:47
Yes, that's correct. I also tried a few different versions of the server. I've updated the parameter it in the config file above which I used to run the sdk

**Comment by Tabrizian** [comment] 2021-07-21 16:50
Model Analyzer in Docker mode uses the exact same container for running your model. It is very strange that it works in one case and not in the other case.

**Comment by aramesh7** [comment] 2021-08-04 17:04
@Deseram if this issue is resolved, please close it.

**Closed** 2021-08-09 13:37 UTC
